name: run_tracker
description: A new Flutter project.

publish_to: 'none'

# Flutter Version :- 3.3.8

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.1
  permission_handler: ^10.2.0
  syncfusion_flutter_gauges: ^20.3.56
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  pedometer: ^3.0.0
  lottie: ^2.0.0
  flutter_rating_bar: ^4.0.1
  floor: ^1.3.0
  path_provider: ^2.0.11
  solid_bottom_sheet: ^0.1.10
  date_picker_timeline: ^1.2.3
  fl_chart: ^0.41.0
  stop_watch_timer: ^2.0.0
  date_format: ^2.0.7
  flutter_local_notifications: ^12.0.3+1
  flutter_native_timezone: ^2.0.0
  charts_flutter: ^0.12.0
  share_plus: ^6.3.0
  url_launcher: ^6.1.6
  auto_size_text: ^3.0.0
  rate_my_app: ^1.1.3
  google_mobile_ads: ^2.3.0
  app_tracking_transparency: ^2.0.3


dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.3.0
  build_runner: ^2.3.2


flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Black.ttf
          weight: 700



  uses-material-design: true

  assets:
   - assets/
   - assets/icons/
   - assets/icons/water/
   - assets/icons/ic_back.png
   - assets/icons/ic_person_walk.png
   - assets/icons/ic_person_run.png
   - assets/icons/ic_footstep.webp
   - assets/icons/ic_steps.png
   - assets/icons/ic_water.png
   - assets/icons/ic_route_map.png
   - assets/icons/ic_best_pace.png
   - assets/icons/ic_distance.webp
   - assets/icons/ic_duration.webp
   - assets/icons/ic_male.png
   - assets/icons/ic_info_white.png
   - assets/icons/ic_female.png
   - assets/icons/ic_select_pointer.png
   - assets/icons/ic_setalite.png
   - assets/icons/ic_person_bottombar.webp
   - assets/icons/ic_map_permission.png
   - assets/icons/ic_setting_circular.png
   - assets/icons/ic_emoji_bad.webp
   - assets/icons/ic_emoji_good.webp
   - assets/icons/ic_emoji_great.webp
   - assets/icons/ic_setting.png
   - assets/icons/ic_emoji_okay.webp
   - assets/icons/ic_emoji_terrible.webp
   - assets/icons/ic_star.webp
   - assets/icons/ic_setting_round.png
   - assets/icons/ic_round_true.webp
   - assets/icons/ic_best_pace_light.webp
   - assets/icons/ic_distance_light.webp
   - assets/icons/ic_duration_light.webp
   - assets/icons/ic_selected_profile_bottombar.webp
   - assets/icons/ic_unselected_profile_bottombar.webp
   - assets/icons/ic_selected_home_bottombar.webp
   - assets/icons/ic_unselected_home_bottombar.webp
   - assets/icons/ic_options.png
   - assets/icons/ic_arrow_green_gradient.png
   - assets/icons/ic_options_steps_indicator.png
   - assets/icons/ic_edit.png
   - assets/icons/ic_reset.png
   - assets/icons/ic_turn_off.png
   - assets/icons/ic_statistics.png
   - assets/icons/ic_star_blue.png
   - assets/icons/ic_trouble_shooting.png
   - assets/icons/ic_yellow_gradient_circle.png
   - assets/icons/ic_red_gradient_circle.png
   - assets/icons/ic_add.png
   - assets/icons/ic_minus.png
   - assets/icons/low_intensity_icon.png
   - assets/icons/modrate_intensity_icon.png
   - assets/icons/high_intensity_icon.png
   - assets/icons/ic_notification_white.webp
   - assets/icons/ic_units.webp
   - assets/icons/ic_calender.webp
   - assets/icons/ic_email.webp
   - assets/icons/ic_languages.webp
   - assets/icons/ic_privacy_policy.webp
   - assets/icons/ic_star_white.webp
   - assets/icons/ic_info.png
   - assets/images/
   - assets/images/dummy_girl.png
   - assets/images/finish_image.png
   - assets/images/bg_countdown_timer_blue.webp
   - assets/images/bg_countdown_timer_green.webp
   - assets/animation/
   - assets/animation/countdown_blue.json
   - assets/animation/countdown_green.json
